# Generated by Django 2.2.3 on 2019-07-21 16:43

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_model', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HealthCare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('RN', 'Registered Nurse'), ('PHYS', 'Physician'), ('PHARM', 'Pharmacist'), ('RT', 'Respiratory Therapist')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('height', models.DecimalField(decimal_places=2, max_digits=6)),
                ('health_conditions', models.TextField()),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pulse_tracer.Device')),
                ('health_care_provider', models.ManyToManyField(to='pulse_tracer.HealthCare')),
            ],
        ),
        migrations.CreateModel(
            name='ROI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.CharField(choices=[('31', 'Right Cheek'), ('35', 'Left Cheek')], max_length=100)),
                ('data', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, max_digits=5), size=None), size=None)),
                ('collection_time', models.DateTimeField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pulse_tracer.Device')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pulse_tracer.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='RespiratoryRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respiratory_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('data', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(blank=True, decimal_places=2, max_digits=5), size=None), size=None)),
                ('collection_time', models.DateTimeField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pulse_tracer.Patient')),
                ('roi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pulse_tracer.ROI')),
            ],
        ),
        migrations.CreateModel(
            name='HeartRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heart_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('data', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(blank=True, decimal_places=2, max_digits=5), size=None), size=None)),
                ('collection_time', models.DateTimeField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pulse_tracer.Patient')),
                ('roi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pulse_tracer.ROI')),
            ],
        ),
    ]
