# Generated by Django 2.2.3 on 2019-11-10 21:28

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_patient', models.BooleanField(default=False)),
                ('is_health_care', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['id'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_model', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HealthCare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('RN', 'Registered Nurse'), ('PHYS', 'Physician'), ('PHARM', 'Pharmacist'), ('RT', 'Respiratory Therapist')], max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=100)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('height', models.DecimalField(decimal_places=2, max_digits=6)),
                ('health_conditions', models.TextField()),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pulse_tracer.Device')),
                ('health_care_provider', models.ManyToManyField(to='pulse_tracer.HealthCare')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ROI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.CharField(choices=[('31', 'Right Cheek'), ('35', 'Left Cheek'), ('27', 'Upper Nose'), ('28', 'Mid-Upper Nose'), ('29', 'Mid-Lower Nose'), ('30', 'Lower Nose'), ('17', 'Left Outer Brow'), ('18', 'Left Mid-Outer Brow'), ('19', 'Left Mid Brow'), ('20', 'Left Mid-Inner Brow'), ('21', 'Left Inner Brow'), ('22', 'Right Inner Brow'), ('23', 'Right Mid-Inner Brow'), ('24', 'Right Mid Brow'), ('25', 'Right Mid-Outer Brow'), ('26', 'Right Outer Brow')], max_length=100)),
                ('batch_id', models.CharField(max_length=100)),
                ('red_data', models.TextField()),
                ('blue_data', models.TextField()),
                ('green_data', models.TextField()),
                ('collection_time', models.DateTimeField(auto_now=True)),
                ('hr_analyzed', models.BooleanField(default=False)),
                ('rr_analyzed', models.BooleanField(default=False)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pulse_tracer.Device')),
            ],
        ),
        migrations.CreateModel(
            name='RespiratoryRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respiratory_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('data', models.TextField()),
                ('analyzed_time', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pulse_tracer.Patient')),
                ('roi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pulse_tracer.ROI')),
            ],
        ),
        migrations.CreateModel(
            name='HeartRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heart_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('data', models.TextField()),
                ('analyzed_time', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pulse_tracer.Patient')),
                ('roi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pulse_tracer.ROI')),
            ],
        ),
    ]
